### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by ThinkingXuan** [xxx0624/AIML-Robot#1]
bitoflife.chatterbean.parser.AliceBotParserException: java.lang.ArrayIndexOutOfBoundsException: 0
	at bitoflife.chatterbean.parser.AliceBotParser.parse(AliceBotParser.java:92)
	at bitoflife.chatterbean.parser.AliceBotParser.parse(AliceBotParser.java:102)
	at bitoflife.chatterbean.AliceBotMother.newInstance(AliceBotMother.java:52)
	at edu.potsdam.App.main(App.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at bitoflife.chatterbean.text.Tokenizer.afterSetProperty(Tokenizer.java:68)
	at bitoflife.chatterbean.text.Tokenizer.setSplitters(Tokenizer.java:156)
	at bitoflife.chatterbean.text.Tokenizer.<init>(Tokenizer.java:48)
	at bitoflife.chatterbean.text.Tokenizer.<init>(Tokenizer.java:53)
	at bitoflife.chatterbean.parser.TransformationsParser.parse(TransformationsParser.java:94)
	at bitoflife.chatterbean.parser.AliceBotParser.newContext(AliceBotParser.java:67)
	at bitoflife.chatterbean.parser.AliceBotParser.parse(AliceBotParser.java:84)
	... 8 more

**Comment by xxx0624** [comment]
你是用的我的代码么 还是reference的？我自己的我试过 是可以的...

**Comment by xxx0624** [comment]
你是用的我的代码么 还是reference的？我自己的我试过 是可以的...
